package menus;


import ProyectoFinal.Nivel1;
import menus.Menu_1;
import java.awt.Toolkit;
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author César Reyes Torres
 */
public class menuNIveles extends javax.swing.JFrame {

    /**
     * Creates new form menuNIveles
     */
    public menuNIveles() {
        
        initComponents();
        transparent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        star1lvl1 = new javax.swing.JLabel();
        star2lvl1 = new javax.swing.JLabel();
        star3lvl1 = new javax.swing.JLabel();
        star1lvl2 = new javax.swing.JLabel();
        star2lvl2 = new javax.swing.JLabel();
        star3lvl2 = new javax.swing.JLabel();
        star1lvl3 = new javax.swing.JLabel();
        star2lvl3 = new javax.swing.JLabel();
        star3lvl3 = new javax.swing.JLabel();
        star1lvl4 = new javax.swing.JLabel();
        star2lvl4 = new javax.swing.JLabel();
        star3lvl4 = new javax.swing.JLabel();
        star1lvl5 = new javax.swing.JLabel();
        star2lvl5 = new javax.swing.JLabel();
        star3lvl5 = new javax.swing.JLabel();
        star1lvl6 = new javax.swing.JLabel();
        star2lvl6 = new javax.swing.JLabel();
        star3lvl6 = new javax.swing.JLabel();
        returnButton = new javax.swing.JButton();
        lvl1button = new javax.swing.JButton();
        lvl2button = new javax.swing.JButton();
        lvl3button = new javax.swing.JButton();
        lvl4button = new javax.swing.JButton();
        lvl5button = new javax.swing.JButton();
        lvl6button = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Angry Birds - Menu");
        setResizable(false);

        panelPrincipal.setPreferredSize(new java.awt.Dimension(1024, 631));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        star1lvl1.setIcon(new javax.swing.ImageIcon("StarLevel.png"));
        panelPrincipal.add(star1lvl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 40, 40));

        star2lvl1.setIcon(new javax.swing.ImageIcon("StarLevel.png"));
        panelPrincipal.add(star2lvl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        star3lvl1.setIcon(new javax.swing.ImageIcon("StarLevel.png"));
        panelPrincipal.add(star3lvl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        star1lvl2.setIcon(new javax.swing.ImageIcon("StarLevel.png"));
        panelPrincipal.add(star1lvl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));

        star2lvl2.setIcon(new javax.swing.ImageIcon("StarLevel.png"));
        panelPrincipal.add(star2lvl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, -1));

        star3lvl2.setIcon(new javax.swing.ImageIcon("StarLevel.png"));
        panelPrincipal.add(star3lvl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, -1, -1));

        star1lvl3.setIcon(new javax.swing.ImageIcon("StarLevel.png"));
        panelPrincipal.add(star1lvl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, -1, -1));

        star2lvl3.setIcon(new javax.swing.ImageIcon("StarLevel.png"));
        panelPrincipal.add(star2lvl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, -1, -1));

        star3lvl3.setIcon(new javax.swing.ImageIcon("StarLevel.png"));
        panelPrincipal.add(star3lvl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, -1, -1));

        star1lvl4.setIcon(new javax.swing.ImageIcon("StarLevel.png"));
        panelPrincipal.add(star1lvl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 40, 40));

        star2lvl4.setIcon(new javax.swing.ImageIcon("StarLevel.png"));
        panelPrincipal.add(star2lvl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, -1, -1));

        star3lvl4.setIcon(new javax.swing.ImageIcon("StarLevel.png"));
        panelPrincipal.add(star3lvl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, -1, -1));

        star1lvl5.setIcon(new javax.swing.ImageIcon("StarLevel.png"));
        panelPrincipal.add(star1lvl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, -1, -1));

        star2lvl5.setIcon(new javax.swing.ImageIcon("StarLevel.png"));
        panelPrincipal.add(star2lvl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, -1, -1));

        star3lvl5.setIcon(new javax.swing.ImageIcon("StarLevel.png"));
        panelPrincipal.add(star3lvl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, -1, -1));

        star1lvl6.setIcon(new javax.swing.ImageIcon("StarLevel.png"));
        panelPrincipal.add(star1lvl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 490, -1, -1));

        star2lvl6.setIcon(new javax.swing.ImageIcon("StarLevel.png"));
        panelPrincipal.add(star2lvl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 490, -1, -1));

        star3lvl6.setIcon(new javax.swing.ImageIcon("StarLevel.png"));
        panelPrincipal.add(star3lvl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 490, -1, -1));

        returnButton.setIcon(new javax.swing.ImageIcon("Return-Button.png"));
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });
        panelPrincipal.add(returnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 535, 100, 90));

        lvl1button.setIcon(new javax.swing.ImageIcon("levelBlock-Front.png"));
        lvl1button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lvl1buttonActionPerformed(evt);
            }
        });
        panelPrincipal.add(lvl1button, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 160, 220));

        lvl2button.setIcon(new javax.swing.ImageIcon("levelBlock-Front.png"));
        lvl2button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lvl2buttonActionPerformed(evt);
            }
        });
        panelPrincipal.add(lvl2button, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 160, 220));

        lvl3button.setIcon(new javax.swing.ImageIcon("levelBlock-Front.png"));
        panelPrincipal.add(lvl3button, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 160, 220));

        lvl4button.setIcon(new javax.swing.ImageIcon("levelBlock-Front.png"));
        panelPrincipal.add(lvl4button, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 160, 220));

        lvl5button.setIcon(new javax.swing.ImageIcon("levelBlock-Front.png"));
        panelPrincipal.add(lvl5button, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 160, 220));

        lvl6button.setIcon(new javax.swing.ImageIcon("levelBlock-Front.png"));
        panelPrincipal.add(lvl6button, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 160, 220));

        background.setIcon(new javax.swing.ImageIcon("Menu-Background.jpg"));
        panelPrincipal.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lvl2buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lvl2buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lvl2buttonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        // TODO add your handling code here:
        Menu_1 cF = new Menu_1();
        cF.setVisible(true);
        dispose();
    }//GEN-LAST:event_returnButtonActionPerformed

    private void lvl1buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lvl1buttonActionPerformed
        // TODO add your handling code here:
        Nivel1 lvl1 = new Nivel1();
        lvl1.setVisible(true);
        lvl1.run();
        dispose();
    }//GEN-LAST:event_lvl1buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuNIveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuNIveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuNIveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuNIveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        new menuNIveles().setVisible(true);

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(() -> {
            new menuNIveles().setVisible(true);
        });*/
    }

    //FUNCIONES ---
    public void transparent(){
        returnButton.setOpaque(false);
        returnButton.setContentAreaFilled(false);
        returnButton.setBorderPainted(false);
        lvl1button.setOpaque(false);
        lvl1button.setContentAreaFilled(false);
        lvl1button.setBorderPainted(false);
        lvl2button.setOpaque(false);
        lvl2button.setContentAreaFilled(false);
        lvl2button.setBorderPainted(false);
        lvl3button.setOpaque(false);
        lvl3button.setContentAreaFilled(false);
        lvl3button.setBorderPainted(false);
        lvl4button.setOpaque(false);
        lvl4button.setContentAreaFilled(false);
        lvl4button.setBorderPainted(false);
        lvl5button.setOpaque(false);
        lvl5button.setContentAreaFilled(false);
        lvl5button.setBorderPainted(false);
        lvl6button.setOpaque(false);
        lvl6button.setContentAreaFilled(false);
        lvl6button.setBorderPainted(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton lvl1button;
    private javax.swing.JButton lvl2button;
    private javax.swing.JButton lvl3button;
    private javax.swing.JButton lvl4button;
    private javax.swing.JButton lvl5button;
    private javax.swing.JButton lvl6button;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JButton returnButton;
    private javax.swing.JLabel star1lvl1;
    private javax.swing.JLabel star1lvl2;
    private javax.swing.JLabel star1lvl3;
    private javax.swing.JLabel star1lvl4;
    private javax.swing.JLabel star1lvl5;
    private javax.swing.JLabel star1lvl6;
    private javax.swing.JLabel star2lvl1;
    private javax.swing.JLabel star2lvl2;
    private javax.swing.JLabel star2lvl3;
    private javax.swing.JLabel star2lvl4;
    private javax.swing.JLabel star2lvl5;
    private javax.swing.JLabel star2lvl6;
    private javax.swing.JLabel star3lvl1;
    private javax.swing.JLabel star3lvl2;
    private javax.swing.JLabel star3lvl3;
    private javax.swing.JLabel star3lvl4;
    private javax.swing.JLabel star3lvl5;
    private javax.swing.JLabel star3lvl6;
    // End of variables declaration//GEN-END:variables
}
