/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProyectoFinal;

import javax.swing.ImageIcon;
import org.dyn4j.samples.framework.SimulationFrame;

/**
 *
 * @author famfi
 */
public class EndGame extends javax.swing.JFrame {

    /**
     * Creates new form EndGame
     */
    
    private Nivel1 daddy;
    
    public EndGame(int score, int stars, int level, int result, SimulationFrame daddy) {
        this.daddy = (Nivel1) daddy;
        this.setVisible(true);
        initComponents();
        if(result == -1){
            lost(); //disables stars, and does not call write on the file
        }else if(result == 1){
            writeFile(score, stars, level);
        }
    }
    
    public EndGame(int score, int stars, int level, int result) {
        this.daddy = (Nivel1) daddy;
        initComponents();
        if(result == -1){
            lost(); //disables stars, and does not call write on the file
        }else if(result == 1){
            writeFile(score, stars, level);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        star1 = new javax.swing.JLabel();
        star2 = new javax.swing.JLabel();
        star3 = new javax.swing.JLabel();
        result = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        OKAY = new javax.swing.JButton();
        pig = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        star1.setIcon(new ImageIcon("StarLevel.png"));
        star1.setText("jLabel1");

        star2.setIcon(new ImageIcon("StarLevel.png"));
        star2.setText("jLabel1");

        star3.setIcon(new ImageIcon("StarLevel.png"));
        star3.setText("jLabel1");

        result.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        result.setText("LEVEL PASSED! ");

        score.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        score.setText("1000000000");

        OKAY.setIcon(new ImageIcon("Return-Button.png"));
        OKAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKAYActionPerformed(evt);
            }
        });

        pig.setIcon(new ImageIcon("Pig2.png"));
        pig.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(score))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(star1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pig, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(star3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(star2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(result))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(OKAY, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(result)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(star2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pig, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(star1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(star3)))
                .addGap(38, 38, 38)
                .addComponent(score)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OKAY, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKAYActionPerformed
        // TODO add your handling code here:
        this.daddy.papa.readScoreFile();
        daddy.dispose();
        this.dispose();
    }//GEN-LAST:event_OKAYActionPerformed
    
    private void lost(){
        star1.setVisible(false);
        star2.setVisible(false);
        star3.setVisible(false);
        pig.setVisible(true);
        result.setText("You lost!");
        score.setText("0");
    }
    
    private void writeFile(int score, int stars, int level){
        pig.setVisible(false);
        if(stars==1){
            star2.setVisible(false);
            star3.setVisible(false);
            
        }else if(stars==2){
            star3.setVisible(false);
        }
        
        this.score.setText(score+"");
        
        //modify the file
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
  
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EndGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EndGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EndGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EndGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EndGame(2000, 0, 1, -1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKAY;
    private javax.swing.JLabel pig;
    private javax.swing.JLabel result;
    private javax.swing.JLabel score;
    private javax.swing.JLabel star1;
    private javax.swing.JLabel star2;
    private javax.swing.JLabel star3;
    // End of variables declaration//GEN-END:variables
}
